name: ItemNameTag
main: com.SapphireDesigns.ItemNameTag.Main
version: 1.3
description: Rename your items using a ItemNameTag!
author: TheCrystalStar
website: http://www.TheCrystalStar.xyz

commands:
  ItemNameTag:
    description: Main command for plugin.
    aliases: [rt, int, rnt, rtag]